#!/usr/bin/env bash
# -*- bash -*-
#

if [[ "$OS" == "Linux" ]]; then
    install_package gnupg
    install_package pinentry-curses
    install_package gnupg-agent
    install_package emacs24-nox
    install_package aspell
    install_package aspell-en
fi

if [[ "$OS" == "FreeBSD" ]]; then
    install_package bash-completion
    install_package aspell
    install_package en-aspell
    install_package emacs-nox11
    install_package go
    install_package python27
fi

if [[ "$OS" == "Darwin" ]]; then
    install_package aspell
    install_package bash-completion
    install_package "emacs --HEAD --cocoa --srgb --use-git-head --with-gnutls"
    install_package go
    install_package leiningen
    install_package markdown
    install_package osxfuse
    install_package pianobar
    install_package s3cmd
    install_package siege
    install_package w3m
    install_package wget
fi
