#!/usr/bin/env bash
# -*- bash -*-
#

if [[ "$OS" == "Linux" ]]; then
    install_package aspell
    install_package aspell-en
    install_package emacs24-nox
    install_package gnupg
    install_package gnupg-agent
    install_package pinentry-curses
fi

if [[ "$OS" == "FreeBSD" ]]; then
    install_package aspell
    install_package bash-completion
    install_package emacs-nox11
    install_package en-aspell
    install_package python27
fi

if [[ "$OS" == "Darwin" ]]; then
    install_package aspell
    install_package bash-completion
    install_package brew-cask
    install_package duplicity
    install_package encfs
    install_package "emacs --with-cocoa --with-gnutls"
    install_package go
    install_package gnupg
    install_package gpg-agent
    install_package jenv
    install_package jq
    install_package leiningen
    install_package markdown
    install_package onepass
    install_package pinentry-mac
    install_package s3cmd
    install_package siege
    install_package the_silver_searcher
    install_package tidyp
    install_package tree
    install_package w3m
    install_package wget
    install_package cask android-file-transfer
    install_package cask appcleaner
    install_package cask crashplan
    install_package cask dropbox
    install_package cask firefox
    install_package cask google-chrome
    install_package cask hermes
    install_package cask java
    install_package cask omnigraffle
    install_package cask omnioutliner-professional3
    install_package cask osxfuse
    install_package cask skype
    install_package cask sublime-text-dev
    install_package cask torbrowser
    install_package cask transmission
    install_package cask virtualbox
    install_package cask viscosity
fi
