#!/usr/bin/env bash
#
# postinstall script

set -o nounset

# programs to install:

if [[ "$OS" == "Linux" ]]; then
    case "$DIST" in
        "Alpine Linux")
            sudo apk update
            sudo apk add \
                 bash-doc \
                 bash-completion \
                 gnupg \
                 pinentry \
                 htop \
                 less \
                 man \
                 man-pages \
                 tmux \
                 wget
            ;;
        "Ubuntu")
            sudo apt-get update
            sudo apt-get install -y \
                 aspell \
                 aspell-en \
                 emacs24-nox
            ;;
    esac
fi

if [[ "$OS" == "FreeBSD" ]]; then
    sudo pkg update
    sudo pkg install -U -y \
         aspell \
         bash-completion \
         direnv \
         emacs-nox \
         en-aspell \
         fzf \
         gnupg \
         jq \
         pinentry \
         pinentry-curses \
         python27 \
         py27-pip \
         py36-pip \
         tmux \
         wget
fi

if [[ "$OS" == "Darwin" ]]; then
    brew update
    brew install \
         aspell \
         bash \
         bash-completion \
         clojure \
         direnv \
         fzf \
         gnupg \
         go \
         hugo \
         jq \
         leiningen \
         markdown \
         mas \
         pinentry-mac \
         pyenv \
         ripgrep \
         rustup-init \
         tmux \
         tree \
         w3m \
         wget
    brew cask install \
         1password-cli \
         appcleaner \
         arq \
         calibre \
         emacs \
         hermes \
         horndis \
         simplenote \
         stay \
         sublime-text \
         vlc
fi
