#!/usr/bin/env bash
#
# postinstall script

set -o nounset

# programs to install:

if [[ "$OS" == "Linux" ]]; then
    case "$DIST" in
        "Alpine Linux")
            sudo apk update
            sudo apk add \
                 bash-doc \
                 bash-completion \
                 gnupg \
                 pinentry \
                 htop \
                 less \
                 man \
                 man-pages \
                 tmux \
                 wget
            ;;
        "Ubuntu")
            sudo apt-get update
            sudo apt-get install -y \
                 aspell \
                 aspell-en \
                 emacs24-nox
            ;;
    esac
fi

if [[ "$OS" == "FreeBSD" ]]; then
    sudo pkg update
    sudo pkg install -U -y \
         aspell \
         bash-completion \
         emacs-nox11 \
         en-aspell \
         python27
fi

if [[ "$OS" == "Darwin" ]]; then
    brew update
    brew install \
         aspell \
         bash \
         bash-completion \
         clojure \
         flake8 \
         fzf \
         gnupg \
         go \
         hugo \
         jq \
         leiningen \
         markdown \
         pinentry \
         pinentry-mac \
         pyenv \
         pyenv-virtualenv \
         pyenv-virtualenvwrapper \
         syncthing \
         syncthing-inotify \
         the_silver_searcher \
         tmux \
         tree \
         w3m \
         wget
    brew cask install \
         appcleaner \
         calibre \
         emacs-mac \
         hermes \
         simplenote \
         stay \
         sublime-text \
         visual-studio-code \
         vlc
fi
